version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "dockerize -wait tcp://db:5432 -timeout 30s
             && python manage.py migrate
             && uwsgi --ini app.ini"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db

volumes:
  postgres_data:
